on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - uses: actions/checkout@v2
      - id: run-action
        uses: sobelow/action@v1
        with:
          flags: '-i Config.CSP'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
